name: Testing

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
  pull_request_target:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "test job"

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event.pull_request.merged == true
    steps:
    - run: echo "build job"
