name: Testing

on:
  push:
    # branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]
  #  types: ["closed"]
  # pull_request_target:
  #  types: ["closed"]
  release:
    type: ["published"]

jobs:
  test:
    runs-on: ubuntu-latest
    # amended the push conditions so this fires on tag push,
    # but NOT the push+merge since this will fire on PR close
    steps:
    - run: echo "test job"

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event.pull_request.merged == true
    steps:
    - run: echo "build job"

  # technically this should be combined with build, this is a test
  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
      # - build
    if: github.event.action == "published"
    steps:
    - run: echo "deploy job"
